server:
    port: 8080
spring:
    jpa:
        show-sql: true  # Spring Data JPA
        hibernate:
            ddl-auto: update
        database: h2
    h2:  # Spring H2
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:file:./src/main/resources/data/employees;AUTO_SERVER=true