server:
    port: 8080
spring:
    jpa:
        hibernate:
            ddl-auto: update        # 設定update值，表示只有第一次載入時需要自動建立資料表，其餘載入則是更新資料表結構
            database-platform: H2   # 設定 JPA database 為 H2 資料庫
            show-sql: true          # 顯示 JPA 運行的SQL語法
            generate-ddl: false
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:file:./src/main/resources/data/tester;AUTO_SERVER=true
        username: sa                # H2 username
        password: changeIt          # H2 password
    thymeleaf:
        cache: false
        encoding: UTF-8
        mode: HTML5
        suffix: .html
        prefix: classpath:/templates/ # 檔案儲存位置