server:
    port: 8080
spring:
    jpa:
        show-sql: true      # Spring Data JPA
        hibernate:
            ddl-auto: update
        database: h2
    h2:                     # Spring H2
        console:
            enabled: true
            path: /h2-console
    datasource:
        url: jdbc:h2:mem:tester;DB_CLOSE_DELAY=-1
        username: sa      # H2 username
        password: changeIt  # H2 password